# Generated by Django 4.0.3 on 2022-05-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=350)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
